#!/bin/sh
### BEGIN INIT INFO
# Provides:          modules-loader
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load/Unoad LDD Kernel Modules
# Description:       This is an init script for loading/unloading ldd modules.
### END INIT INFO

# Function to start the service
start() {
    echo "Loading modules..."
    /etc/init.d/scull_load
    echo "scull loaded successfully."
    echo "Loading modules..."
    /etc/init.d/module_load faulty
    echo "module loaded successfully."
    modprobe hello
    echo "hello module loaded successfully."
}

# Function to stop the service
stop() {
    echo "Unloading modules..."
    /etc/init.d/scull_unload
    echo "scull unloaded successfully."
    echo "Unloading modules..."
    /etc/init.d/module_unload
    echo "module unloaded successfully."
    rmmod hello
    echo "hello module unloaded successfully."
}

# Script execution starts here
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
